export const stats = [
  { value: 50000, suffix: "+", label: "Jobs Available" },
  { value: 5000, suffix: "+", label: "Verified Companies" },
  { value: 200000, suffix: "+", label: "Registered Candidates", display: "2,00,000+" },
  { value: 98, suffix: "%", label: "Placement Success" },
];

export const companies = [
  {
    id: "google",
    name: "Google",
    industry: "Technology",
    openJobs: 42,
    rating: 4.8,
    logo: "G",
    logoUrl: "https://logo.clearbit.com/google.com",
    domain: "google.com",
    color: "#4285F4",
    location: "Bengaluru",
    description: "Organize the world's information and make it universally accessible.",
  },
  {
    id: "amazon",
    name: "Amazon",
    industry: "E-Commerce",
    openJobs: 67,
    rating: 4.5,
    logo: "A",
    logoUrl: "https://logo.clearbit.com/amazon.com",
    domain: "amazon.com",
    color: "#FF9900",
    location: "Hyderabad",
    description: "Earth's most customer-centric company.",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    industry: "Technology",
    openJobs: 38,
    rating: 4.7,
    logo: "M",
    logoUrl: "https://logo.clearbit.com/microsoft.com",
    domain: "microsoft.com",
    color: "#00A4EF",
    location: "Hyderabad",
    description: "Empower every person and organization to achieve more.",
  },
  {
    id: "infosys",
    name: "Infosys",
    industry: "IT Services",
    openJobs: 120,
    rating: 4.2,
    logo: "I",
    logoUrl: "https://logo.clearbit.com/infosys.com",
    domain: "infosys.com",
    color: "#007CC3",
    location: "Bengaluru",
    description: "Navigate your next with digital transformation.",
  },
  {
    id: "tcs",
    name: "TCS",
    industry: "IT Services",
    openJobs: 210,
    rating: 4.1,
    logo: "T",
    logoUrl: "https://logo.clearbit.com/tcs.com",
    domain: "tcs.com",
    color: "#0B4F8A",
    location: "Mumbai",
    description: "Building on belief through technology and consulting.",
  },
  {
    id: "accenture",
    name: "Accenture",
    industry: "Consulting",
    openJobs: 95,
    rating: 4.3,
    logo: "Ac",
    logoUrl: "https://logo.clearbit.com/accenture.com",
    domain: "accenture.com",
    color: "#A100FF",
    location: "Pune",
    description: "Let there be change — strategy, consulting, digital and operations.",
  },
  {
    id: "wipro",
    name: "Wipro",
    industry: "IT Services",
    openJobs: 88,
    rating: 4.0,
    logo: "W",
    logoUrl: "https://logo.clearbit.com/wipro.com",
    domain: "wipro.com",
    color: "#341C8E",
    location: "Bengaluru",
    description: "Applying thought to deliver technology solutions.",
  },
  {
    id: "ibm",
    name: "IBM",
    industry: "Technology",
    openJobs: 54,
    rating: 4.4,
    logo: "IBM",
    logoUrl: "https://logo.clearbit.com/ibm.com",
    domain: "ibm.com",
    color: "#054ADA",
    location: "Bengaluru",
    description: "Let's create technology that changes the world.",
  },
  {
    id: "deloitte",
    name: "Deloitte",
    industry: "Consulting",
    openJobs: 73,
    rating: 4.5,
    logo: "D",
    logoUrl: "https://logo.clearbit.com/deloitte.com",
    domain: "deloitte.com",
    color: "#86BC25",
    location: "Gurugram",
    description: "Making an impact that matters for clients and communities.",
  },
  {
    id: "capgemini",
    name: "Capgemini",
    industry: "IT Consulting",
    openJobs: 61,
    rating: 4.2,
    logo: "C",
    logoUrl: "https://logo.clearbit.com/capgemini.com",
    domain: "capgemini.com",
    color: "#0070AD",
    location: "Mumbai",
    description: "Get the future you want with digital transformation.",
  },
];

export const jobs = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Google",
    companyId: "google",
    location: "Bengaluru, Karnataka",
    salary: { min: 2800000, max: 4500000 },
    experience: "4-7 years",
    type: "Full-time",
    mode: "Hybrid",
    posted: "2 days ago",
    skills: ["React", "TypeScript", "Next.js"],
    logo: "G",
    color: "#4285F4",
  },
  {
    id: "2",
    title: "Product Manager",
    company: "Amazon",
    companyId: "amazon",
    location: "Hyderabad, Telangana",
    salary: { min: 3200000, max: 5000000 },
    experience: "5-9 years",
    type: "Full-time",
    mode: "On-site",
    posted: "1 day ago",
    skills: ["Roadmaps", "Analytics", "Agile"],
    logo: "A",
    color: "#FF9900",
  },
  {
    id: "3",
    title: "Cloud Solutions Architect",
    company: "Microsoft",
    companyId: "microsoft",
    location: "Hyderabad, Telangana",
    salary: { min: 3500000, max: 5500000 },
    experience: "6-10 years",
    type: "Full-time",
    mode: "Hybrid",
    posted: "3 days ago",
    skills: ["Azure", "DevOps", "Architecture"],
    logo: "M",
    color: "#00A4EF",
  },
  {
    id: "4",
    title: "Java Full Stack Developer",
    company: "Infosys",
    companyId: "infosys",
    location: "Pune, Maharashtra",
    salary: { min: 1200000, max: 2200000 },
    experience: "3-6 years",
    type: "Full-time",
    mode: "Hybrid",
    posted: "5 hours ago",
    skills: ["Java", "Spring Boot", "React"],
    logo: "I",
    color: "#007CC3",
  },
  {
    id: "5",
    title: "Data Scientist",
    company: "TCS",
    companyId: "tcs",
    location: "Mumbai, Maharashtra",
    salary: { min: 1500000, max: 2800000 },
    experience: "2-5 years",
    type: "Full-time",
    mode: "Remote",
    posted: "4 days ago",
    skills: ["Python", "ML", "SQL"],
    logo: "T",
    color: "#0B4F8A",
  },
  {
    id: "6",
    title: "UX Design Lead",
    company: "Accenture",
    companyId: "accenture",
    location: "Bengaluru, Karnataka",
    salary: { min: 2000000, max: 3500000 },
    experience: "5-8 years",
    type: "Full-time",
    mode: "Hybrid",
    posted: "1 week ago",
    skills: ["Figma", "Research", "Design Systems"],
    logo: "Ac",
    color: "#A100FF",
  },
];

export const howItWorks = [
  { step: 1, title: "Create Account", description: "Sign up with your email and verify with OTP." },
  { step: 2, title: "Complete Profile", description: "Add your details and upload your resume." },
  { step: 3, title: "Choose a Job", description: "Browse companies and select the role you want." },
  { step: 4, title: "Fill Application Form", description: "Complete the job-specific application fields." },
  { step: 5, title: "Pay & Submit", description: "Pay the application fee securely and submit your application." },
];

export const whyChooseUs = [
  { title: "Verified Companies", description: "Every employer is thoroughly vetted for authenticity." },
  { title: "Safe Platform", description: "Your data is encrypted and never shared without consent." },
  { title: "Fast Hiring", description: "Average time-to-interview under 7 days for active seekers." },
  { title: "Resume Builder", description: "Create ATS-friendly resumes with our smart builder." },
  { title: "Career Guidance", description: "Expert tips and personalized career roadmaps." },
  { title: "Interview Support", description: "Mock interviews and preparation resources included." },
  { title: "24/7 Support", description: "Round-the-clock help whenever you need assistance." },
];

export const testimonials = [
  {
    name: "Priya Sharma",
    role: "Software Engineer at Google",
    avatar: "PS",
    quote:
      "JobCareerPao helped me land my dream role at Google within 3 weeks. The apply-and-track flow was simple and fast.",
    rating: 5,
  },
  {
    name: "Rahul Mehta",
    role: "Product Manager at Amazon",
    avatar: "RM",
    quote:
      "The platform's verified companies and clean UI made job hunting feel premium. I received multiple interview calls in days.",
    rating: 5,
  },
  {
    name: "Ananya Patel",
    role: "Data Scientist at Microsoft",
    avatar: "AP",
    quote:
      "From resume upload to fee payment, everything was on one platform. I switched into AI/ML roles smoothly.",
    rating: 5,
  },
  {
    name: "Vikram Singh",
    role: "Full Stack Developer at Infosys",
    avatar: "VS",
    quote:
      "I signed up, picked a job, filled the form, paid the fee, and tracked my application — all in minutes.",
    rating: 5,
  },
];

export { blogPosts } from "./blog";

export const footerLinks = {
  quick: [
    { label: "Home", href: "/" },
    { label: "Jobs", href: "/jobs" },
    { label: "Companies", href: "/companies" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],
  company: [
    { label: "About", href: "/about" },
    { label: "Careers", href: "/careers" },
    { label: "Contact", href: "/contact" },
    { label: "FAQ", href: "/faq" },
  ],
  legal: [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Terms", href: "/terms" },
    { label: "Refund Policy", href: "/refund" },
  ],
  candidates: [
    { label: "Browse Jobs", href: "/jobs" },
    { label: "Companies", href: "/companies" },
    { label: "Career Blog", href: "/blog" },
    { label: "My Profile", href: "/profile" },
  ],
};