import PDFDocument from "pdfkit";
import type { ProfileSnapshot } from "@/lib/resume/profile";

function addSection(doc: InstanceType<typeof PDFDocument>, title: string, body: string) {
  if (!body.trim()) return;
  doc.moveDown(0.5).fontSize(12).fillColor("#0B4F8A").text(title, { underline: true });
  doc.moveDown(0.25).fontSize(10).fillColor("#333333").text(body, { lineGap: 4 });
}

export async function generateProfilePdfBuffer(profile: ProfileSnapshot): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk) => chunks.push(chunk as Buffer));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).fillColor("#0B4F8A").text(profile.name, { align: "left" });
    doc.moveDown(0.25);
    doc.fontSize(10).fillColor("#555555");
    doc.text(`${profile.email}  |  ${profile.phone}`);
    const address = [
      profile.address?.line1,
      profile.address?.city,
      profile.address?.state,
      profile.address?.pincode,
      profile.address?.country,
    ]
      .filter(Boolean)
      .join(", ");
    if (address || profile.location) {
      doc.text(address || profile.location || "");
    }

    if (profile.bio) {
      addSection(doc, "Professional Summary", profile.bio);
    }

    if (profile.skills?.length) {
      addSection(doc, "Skills", profile.skills.join(" • "));
    }

    if (profile.languages?.length) {
      addSection(doc, "Languages", profile.languages.join(" • "));
    }

    if (profile.experience?.length) {
      const expText = profile.experience
        .map((item) => {
          const dates = item.current
            ? `${item.startDate} – Present`
            : `${item.startDate}${item.endDate ? ` – ${item.endDate}` : ""}`;
          return `${item.title} at ${item.company} (${dates})${item.description ? `\n${item.description}` : ""}`;
        })
        .join("\n\n");
      addSection(doc, "Experience", expText);
    }

    if (profile.education?.length) {
      const eduText = profile.education
        .map(
          (item) =>
            `${item.degree}, ${item.institution} (${item.year})${item.grade ? ` — ${item.grade}` : ""}`
        )
        .join("\n");
      addSection(doc, "Education", eduText);
    }

    doc.moveDown(1);
    doc.fontSize(8).fillColor("#888888").text(
      `Generated by JobCareerPao on ${new Date(profile.capturedAt).toLocaleDateString("en-IN")}`,
      { align: "center" }
    );

    doc.end();
  });
}
